### ISSUE TITLE
Auto-Rename existed file with file mask

### ISSUE THREAD

**Issue by Jeredian** [Jeredian/mks-wifi-plugin#10]
add to plugin settings mask to an auto-rename new file if older one exists.

**Comment by vicodin77** [comment]
А когда можно ожидать появления данного функционала?

**Comment by Jeredian** [comment]
После праздников, как только появится свободное время. Надеюсь до окончания января.

**Comment by Elkin-Vasily** [comment]
This is fixed in #66
