### ISSUE TITLE
[FEATURE] Implement model image size configuration

### ISSUE THREAD

**Issue by Jeredian** [Jeredian/mks-wifi-plugin#107]
After we fixed the wrong preview of the model, we need to add the possibility to configure different sizes of the model screenshot.
This config will display information about printer series and fill their sizes into settings.

There should be:

- None: (null, null)
- Base size : (simage:100, gimage:200)
- Two Trees Sapphire: (simage:100, gimage:200)
- Flying Bear : (simage:50, gimage:100)
- FLSUN QQ-S: (null, null)

**Comment by Jeredian** [comment]
this issue based on #11 , #45 , #80

**Comment by moryak-89** [comment]
Hello, I selected the following values for FlyingBear Ghost 5: simage 50; gimage 200. Didn't work with values 50 and 100
