### ISSUE TITLE
The model preview in does not work correctly. (Cura version 4.4.1, plugin version 1.0.2)

### ISSUE THREAD

**Issue by Error26** [Jeredian/mks-wifi-plugin#11]
The previous model review does not work correctly. 
I have MKS TFT35 v1.0 firmware 1.0.2.
Cura version 4.4.1 Plugin version 1.0.2.
![IMG_20200110_140317](https://user-images.githubusercontent.com/31626085/72271634-ea456280-362f-11ea-890c-e6c40811e897.jpg)
![IMG_20200110_140328](https://user-images.githubusercontent.com/31626085/72271635-ea456280-362f-11ea-9c77-b6433c838d15.jpg)

**Comment by Error26** [comment]
I can give an old version of Cura with a working plugin.
https://drive.google.com/open?id=19DTEfol_n55qEbuVwAuwZxx4jwVb4mWJ

**Comment by Jeredian** [comment]
I seems that your preview image size is different than mine.  Because we have different firmware.
I can suggest some simple steps to find your preview size. And I will add it in future releases of the plugin (something like select box for preview size in the plugin popup).
So here are the steps:
1. Close Cura.
2. Go to Plugin folder.
Open the Cura configuration folder. It can be found via Help -> Show Configuration Folder inside Cura.  After that go to "plugins -> MKSWifiPlugin -> MKSWifiPlugin" folder.
3. Find file "SaveOutputDevice.py" and open it in notepad, or code line editor (like VSCode)
4. Find the line with code `save_file.write(utils.add_screenshot(image, 50, 50, ";simage:"))` . It's near line 120.
5. Change the size to a little bit bigger (f.ex. like 100, or 75) for "simage". Pair of numbers should be the same (75, 75 or 100, 100)
6. Save file changes
7. Run Cura, and send the sliced model to the printer again.

You can play with size, find acceptable for your firmware. When a new preview will look fine let me know, about the size of the image.
It's a little workaround until the next plugin release.

**Comment by Jeredian** [comment]
If the older version of the plugin works for you, there will be size like this
`save_file.write(utils.add_screenshot(image, 100, 100, ";simage:"))`.

**Comment by Error26** [comment]
Thank you.

**Comment by sizanjavad** [comment]
> I seems that your preview image size is different than mine. Because we have different firmware.
> I can suggest some simple steps to find your preview size. And I will add it in future releases of the plugin (something like select box for preview size in the plugin popup).
> So here are the steps:
> 
> 1. Close Cura.
> 2. Go to Plugin folder.
>    Open the Cura configuration folder. It can be found via Help -> Show Configuration Folder inside Cura.  After that go to "plugins -> MKSWifiPlugin -> MKSWifiPlugin" folder.
> 3. Find file "SaveOutputDevice.py" and open it in notepad, or code line editor (like VSCode)
> 4. Find the line with code `save_file.write(utils.add_screenshot(image, 50, 50, ";simage:"))` . It's near line 120.
> 5. Change the size to a little bit bigger (f.ex. like 100, or 75) for "simage". Pair of numbers should be the same (75, 75 or 100, 100)
> 6. Save file changes
> 7. Run Cura, and send the sliced model to the printer again.
> 
> You can play with size, find acceptable for your firmware. When a new preview will look fine let me know, about the size of the image.
> It's a little workaround until the next plugin release.

worked for me. thank you.

**Comment by Operrr** [comment]
Many thanks to the author. Everything is fine.

**Comment by Bradley-Liu** [comment]
Cura 4.6 not working I am using 1.0.5 version tft35 preview not working

**Comment by Elaugaste** [comment]
Привет, извините что по русски, мой инглиш слишком плох. 

Было бы крайне здорово сделать формирование превью опциональным, т.к. существуют принтеры которые не умеют адекватно переваривать лишний хлам в файле с гкодом. 

MKS Robin mini например внезапно может забурится соплом в стол или пытаться унести голову за аппаратные пределы

**Comment by Jeredian** [comment]
@Bradley-Liu , new Cura has a little bit different API. I'll update the plugin on next week to support the new version, and also with fixes for preview.

**Comment by Jeredian** [comment]
@Elaugaste , Добрый вечер. Рад что у Вас получилось разобраться до того нового релиза.
Если не сложно то сделайте пулл реквест в мой репозиторий, и в выходные, либо на следующей неделе он будет доступен через cura marketplace

**Comment by Elaugaste** [comment]
@Jeredian 
пулл реквест сделал, но я отфорковался не от вашего мастера а от другого форка.
потому там только последний коммит содержит нужные изменения...

**Comment by karabas2011** [comment]
плагин будет коннектиться к произвольному принтеру с MKS TFT35 + MKS wifi?
Cura 4.6.1 не коннектится и не видит номер  прошивки

**Comment by Jeredian** [comment]
@karabas2011 , по идее должен.  Более развернуто могут ответить разработчики makerbase я думаю. либо спроси в группе https://t.me/K_3_D

Номер прошивки не видит потому что makerBase не прикрутили это. в ближайших релизах возможно сами допилим.

**Comment by Jeredian** [comment]
@karabas2011 , сама по себе Cura не умеет соединяться с принтером , а плагин может только к тем кого видит в своей подсети, конечно с учетом что это MKS TFT35,  и в идеале плата mks robin

**Comment by karabas2011** [comment]
ну да плагин я поставил, зайти на вайфайку могу броузером или пронтерфейсом, то есть она доступна по сети.

**Comment by karabas2011** [comment]
кстати если коннектиться пронтерфейсом половина команд не отзывается. например M119, M503  и тд. а M105 отзвается. M115 выводит строку самой вайфайки. Интересно есть способ насквозь команды пропускать в принтер?

**Comment by Jeredian** [comment]
@karabas2011 , может у тебя плата какая специфичная ?
вроде как там просто команды должны посылаться на плату, и обратный ответ от нее

**Comment by Jeredian** [comment]
@karabas2011 ,  касательно команду думаю надо создавать issue тут : https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT3.5

**Comment by Jeredian** [comment]
@karabas2011 , про подключение через Cura - распиши как ты это делал, может какой то шаг пропустил. 
Если что авто поиск принтера в сети пока еще не добавлен, там надо в ручную ip принтера указывать. и потом нажимать connect button

**Comment by karabas2011** [comment]
так а там собственно нечего делать. как только плагин поставил он тут же вписался в текущий принтер как кнопка MKS WIFI. Нажал - ввёл IP  а дальше фиг.

**Comment by Elaugaste** [comment]
логи куры нужно смотреть

**Comment by karabas2011** [comment]
таймаут и реконнекты

**Comment by karabas2011** [comment]
подробностей не пишет.

**Comment by Elaugaste** [comment]
@karabas2011 попробуйте прожать telnet на порт 8080.  Плагин стучится в него,  возможно у вас на другой порт нужно ходить

**Comment by adripo** [comment]
I have a similar error 

> 
> 
> I seems that your preview image size is different than mine. Because we have different firmware.
> I can suggest some simple steps to find your preview size. And I will add it in future releases of the plugin (something like select box for preview size in the plugin popup).
> So here are the steps:
> 
>     1. Close Cura.
> 
>     2. Go to Plugin folder.
>        Open the Cura configuration folder. It can be found via Help -> Show Configuration Folder inside Cura.  After that go to "plugins -> MKSWifiPlugin -> MKSWifiPlugin" folder.
> 
>     3. Find file "SaveOutputDevice.py" and open it in notepad, or code line editor (like VSCode)
> 
>     4. Find the line with code `save_file.write(utils.add_screenshot(image, 50, 50, ";simage:"))` . It's near line 120.
> 
>     5. Change the size to a little bit bigger (f.ex. like 100, or 75) for "simage". Pair of numbers should be the same (75, 75 or 100, 100)
> 
>     6. Save file changes
> 
>     7. Run Cura, and send the sliced model to the printer again.
> 
> 
> You can play with size, find acceptable for your firmware. When a new preview will look fine let me know, about the size of the image.
> It's a little workaround until the next plugin release.

I have a similar error, but this didn't help.

My image is translated and have strange colors.
Have a look
![photo_2020-05-29_21-01-33](https://user-images.githubusercontent.com/26493496/83295643-96f33b80-a1ef-11ea-9a07-6f00e0a313ec.jpg)

**Comment by Jeredian** [comment]
Hi, @adripo , you can try to use different values "50, 50",  "75, 75",  "100, 100".
At next releases, I hope, I will add select box for that size

**Comment by adripo** [comment]
I tried 25, 50, 75, 100, 200 but nothing changed. Every time I diconeected, closed cura, changed value, reopened cura, connected, slice and send.
Do you have any other idea?
Thanks

**Comment by Jeredian** [comment]
There is 2 places with image sizing:
1. SaveOutputDevice.py  - line 120
2. MKSOutputDevice.py - line 619

As first step it's to set both of them for simage - as 100
the second one try to comment both lines and check will image disappear or not

That's a very simple bug, but it's hard to implement selector for different sizes inside QML file, without project .pro file.. because qt designer can't import uranium framework and cura engine to preview form
If this two steps didn't help, let me know I'll try to speed up work on this task.

**Comment by adripo** [comment]
Thank you for the fast reply!
I changed the value (to 50) also in MKSOutputDevice and now the picture is perfect.
Thanks for the help.
Can you explain me better how is this programmed? Maybe I can help you. I had a look at qt designer. How does this interface with cura? Can you share any documentation with me please?

**Comment by Jeredian** [comment]
In short, it makes an image with selected size and puts it at the start of gcode file. When printer will open gcode file, the image will be treated and you can saw it at the screen.
About UI, it's all qml files inside the project. MKSConnectBtn.qml - seems to be UI where we can place select box with sizes (small, medium, large), these settings can be saved as we used in the printer IP list.
Also, you can look at Cura wiki, to ger information about the environment and references.
https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source
https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices

**Comment by dreamerenigma** [comment]
Hello everyone, in Cura version 4.8 there is no line save_file.write (utils.add_screenshot (image, 50, 50, "; simage:")) in the SaveOutputDevice.py file. Perhaps the new version of Cura does not support the preview window.

**Comment by Jeredian** [comment]
Hi @Volt-AmperAI , SaveOutputDevice.py - it's not Cura, it's our plugin code.
Since the latest release, we moved model preview to the plugin settings window. Please check it out

**Comment by dreamerenigma** [comment]
MKSWIFI plugins version
<a href="https://fastpic.ru/view/114/2021/0413/dfbab88a21ed0bb561da6f7d7f216d30.png.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0413/30/dfbab88a21ed0bb561da6f7d7f216d30.jpeg" border="0"></a>
The problem is that the image goes beyond the boundaries of the TFT35 v1.0 screen. And for some reason, artifacts on the screen. This is if you save to TFT in Cura.
<a href="https://fastpic.ru/view/114/2021/0413/a5b7f4c0b224c951700a1b9d7e4a81db.jpeg.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0413/db/a5b7f4c0b224c951700a1b9d7e4a81db.jpeg" border="0"></a>
<a href="https://fastpic.ru/view/114/2021/0413/668ef08e07e842921b6248471771b29c.jpeg.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0413/9c/668ef08e07e842921b6248471771b29c.jpeg" border="0"></a>

**Comment by Jeredian** [comment]
@Volt-AmperAI , you should select the correct screenshot settings. There are several of them (base, none, and for some printer models). If none of them will be correct for you, you can create an issue for it, and if you know the correct size values, you also can make a PR. 
![image](https://user-images.githubusercontent.com/9591166/114527493-b6048b80-9c50-11eb-91fe-8aa90bbb9f70.png)
![image2](https://user-images.githubusercontent.com/9591166/114527514-bdc43000-9c50-11eb-9ca8-bf3f563ea5c7.png)

**Comment by dreamerenigma** [comment]
my printer does not go online at all, the MKSWIFI module is working, the phone sees it, but for some reason the plugin does not work in Cura, maybe the MKSWIFI plugin does not work in Cura 4.8? Maybe someone knows?
<a href="https://fastpic.ru/view/114/2021/0413/ce2d08d85bff32a3374c486957b8f5f1.png.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0413/f1/ce2d08d85bff32a3374c486957b8f5f1.jpeg" border="0"></a>

**Comment by Jeredian** [comment]
@Volt-AmperAI , 
1. Remove IP of your current printer
2. Restart the Cura
3. Add new IP and press connect button.

FYI, for that type of questions, I suggest to you ask it at telegram channel https://t.me/mks_wifi_plugin_dev

**Comment by dreamerenigma** [comment]
Does not connect to the network, does not find a specific IP address. Although the IP address is indicated on the phone, the same as I enter in Cura
<a href="https://fastpic.ru/view/114/2021/0413/e9e5eb5f929abe53c33972f1dca50f1f.jpeg.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0413/1f/e9e5eb5f929abe53c33972f1dca50f1f.jpeg" border="0"></a>
