### ISSUE TITLE
[FEATURE] MKS Home Assistant integration

### ISSUE THREAD

**Issue by willpuckett** [Jeredian/mks-wifi-plugin#127]
**Is your feature request related to a problem? Please describe.**

This might be a long one, but I thought it would be worth mentioning. There's a obviously a lot of domain knowledge in this repository about MKS. 

Currently, I install Octoprint to manage and monitor my printers in Home Assistant. This lets me log be easily monitor several printers at once, and do things like turn them off when they finish printing.

**Describe the solution you'd like**

It would be exhilarating to see this project ported/refactored into a home assistant integration that would expose sensor data to home assistant. Including gcode upload and job progress/ control would be icing on the cake.

**Describe alternatives you've considered**

I currently use octoprint to deal with this, but reducing cost and using the already on board hardware would be preferable be more environmentally friendly. 

**Additional context**

This is the current octoprint equivalent to what it would be exciting to see with MKS: https://github.com/cmroche/OctoPrint-HomeAssistant

**Comment by Jeredian** [comment]
Hi, @willpuckett .
That's a great idea, let's keep it for the future. Maybe someone who already has Home Assistant will start development in that way.

**Comment by gumileeev** [comment]
Hello! I also really want to see integration into the homeassistant for flying bear ghost 5. If the homeassistant receives statuses from the printer, it will be easy to make flattering the printer more comfortable: receive a telegram notification about the end of work, notify about errors, turn off the hood, and more.

**Comment by snoopomsk** [comment]
Supporting that feature request as well. Also having Flying Bear Ghost 5 and really suprised that there is no  HASS integration for it.

**Comment by necroave** [comment]
Wold be nice if mkswifi will be supported and have home assistant plug in.

**Comment by CoolRinat** [comment]
It would be a cool feature. I also have FlyingBear Ghost 5 and HA instance. And I really need awareness of how the printer works remotely. thx

**Comment by Jeredian** [comment]
It's simpler to create an additional app than a plugin for HomeAssistant.  But I'm not sure that someones are ready to pay for it.

**Comment by Elkin-Vasily** [comment]
There is such project by @Blooof.

[Here it is.](https://github.com/Blooof/Mks2MqttReporter)
