### ISSUE TITLE
[BUG] The file transfer window disappears immediately

### ISSUE THREAD

**Issue by Malderin** [Jeredian/mks-wifi-plugin#128]
Не понимаю в чем дело, но в куре 4.8 при отправке на печать файла, окно передачи (то что с галкой "начать печать автоматически после передачи") появляется бувально на секунду и исчезает. Галку при таком раскладе снять нереально. При этом на экране принтера появляется стандартный интерфейс передачи файла, файл передается и печать стартует (галка видимо стоит).
Есть мысли что сделать? Плагин переустанавливал.

> Eng
> I don't know what's wrong, but in Cura 4.8, when you send a file to print, the transfer window (the one with the checkmark "start printing automatically after transfer") appears for about a second and then disappears. It is impossible to uncheck the box in this case. In doing so, the printer screen displays the standard file transfer interface, the file is transferred, and the print starts (there seems to be a checkmark in the box).
> Any idea what to do?

**Comment by Malderin** [comment]
Забыл. Для чистоты эксперимента поставил куру с нуля, добавил профиль эндер-2, установил из маркета вайфай плагин. Никакие настройки не трогал - проблема осталась.
Возможно это важно, раньше на вин7 проблем не было, сейчас на вин 10 перешел и эта проблема появилась.

**Comment by Jeredian** [comment]
@Malderin ,
Для того чтобы было возможно понять Вашу проблему необходимы дополнительные данные:
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, macOS 11.1]
 - Cura version: [e.g. 4.8.0]
 - Plugin version: [e.g. 1.1.2]
 - 3D printer: [e.g. FlyingBear Ghost 5]
 - Motherboard and/or WiFi module firmware version: [e.g. V5.8/V5.8]
 
 А также необходим **файл логов**:
 - Windows: %APPDATA%\cura\<Cura version>\cura.log , or C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log
 - OSX: $USER/Library/Application Support/cura/<Cura version>/cura.log
 - Ubuntu / Linux:$USER/.local/share/cura/<Cura version>/cura.log

> Eng
> In order to be able to understand your problem, **additional data** and **log file** are needed.

**Comment by Malderin** [comment]
> Для того чтобы было возможно понять Вашу проблему необходимы дополнительные данные:
> **Desktop (please complete the following information):**

**OS:** 
Выпуск	Windows 10 Pro
Версия	20H2
Дата установки	‎08.‎02.‎2021
Сборка ОС	19042.685
Взаимодействие	Windows Feature Experience Pack 120.2212.551.0
**Cura version:** 4.8.0
**Plugin version:** 1.2.0
**3D printer**: KingRoon KP3 (Хотя это значения не имеет, т.к. плата там не родная)
**Motherboard and/or WiFi module firmware version:** : MKS Robin nano v.2, а вот прошивка вайфай модуля стояла с завода, ничего не менял и какая версия даже и не знаю. При покупке на сайте продавца было сказано что прошивка залита и обновлять ничего не нужно.

> А также необходим **файл логов**:

[cura.zip](https://github.com/Jeredian/mks-wifi-plugin/files/6053836/cura.zip)

И вот как это выглядит, видос снял:
https://yadi.sk/i/mqMNN3_ORL19qA

**Comment by Malderin** [comment]
Обновил модуль вайфай до последней версией прошивки с гитхаба (1.0.4) - никаких изменений

**Comment by Jeredian** [comment]
@Malderin , Судя по видео, у Вас просто очень быстро передаются файлы. т.к. сразу после передачи началась печать.
Попробуйте для сравнения большую и сложную модель перекинуть, тогда у вас будет сообщение об отправке не сразу исчезать. Дайте знать о том какое поведение будет в данном случае.

На данный момент есть два варинта решения задачи:
1. Добавить задержку перед отправкой на печать, в виде 1-2 секунд по умолчанию, и настройкой в окне плагина. 
2. Вынести чекбокс с началом печати в настройки плагина чтобы настроить это в статичном окне и для любой отправки на печать.

> Eng
> @Malderin, From your video, it looks like your files are transferring very quickly because right after the transfer, the printing was started. Try to transfer a large and complex model for comparison, then you will have the sending message not immediately disappear. And please, let me know what the behavior will be in this case.
> 
> At the moment there are two possible solutions to the issue:
> 1. Add a delay before sending to print, in 1-2 seconds by default, and implement this setting in the plugin window. 
> 2. Put a checkbox with the beginning of printing in the settings of the plugin to configure it in a static window and for any sending to print.

**Comment by Malderin** [comment]
> Судя по видео, у Вас просто очень быстро передаются файлы

Ах если б это было так. На самом деле в начале появляется просто бегающая полоса (типа подготовки к загрузке) - ее и видно на видео, потом должна появиться полоса загрузки, но она не появляется, сразу проскакивает на окно типа все передано. 


> 2\. Вынести чекбокс с началом печати в настройки плагина чтобы настроить это в статичном окне и для любой отправки на печать.


Вот реально огромная модель:
https://yadi.sk/i/SQSi-EOKS51yDA
Экран принтера не снял, но там еще пару минут висело окно передачи, прежде чем появился диалог печати (если что могу переснять).

А вот это было б хорошо вообще в любом случае, даже без привязки к моей проблеме.
П. 1 проблему не решит, она не в этом как я написал выше, но для опции настройки плагина, как по мне, не помешал бы.

**Comment by Jeredian** [comment]
Согласен, исходя из второго видео, у нас процесс отправки модели на принтер не соответствует реальной скорости отправки.

Так что да, будет комплексное решение:
1. Проверить процесс отправки, и выяснить почему он завершается до рельного получения файла на принтере, т.к потенциально могут буть проблемы начала печати, при закрытии Cura, либо отправки команды на печать, до того как файл был отправлен.
2. Вынести чекбокс для отправки на печать в настройки. т.к. потенциально пользователь может не успеть принять решение при отправке файла, либо изменит его когда файл уже отправлен.

> Eng
> I agree, based on the second video, our process of sending gcode file to the printer not according to the actual speed of sending.
> 
> So, yeah, better will be making a complex solution:
> 1. Check the sending process and find out why it completes before the file is received on the printer. There can be potential issues with print starting when Cura closed after the file sent, or with sending a command to print before the file was received on the printer.
> 2. Add checkbox to "start print" in the plugin settings. Because there can be the case when a user may not have time to make a decision or may try to change settings when a command to print complete

**Comment by Malderin** [comment]
Если нужны какие то дополнительные данные или логи, я всегда готов все предоставить.

**Comment by Elkin-Vasily** [comment]
Судя по логу у Вас происходит следующее:

2021-02-27 09:29:30,215 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice._onUploadProgress [840]: Upload _onUploadProgress bytes_sent 16384
2021-02-27 09:29:30,215 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice._onUploadProgress [842]: Upload _onUploadProgress bytes_total 399091
2021-02-27 09:29:30,221 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice._onUploadProgress [840]: Upload _onUploadProgress bytes_sent 399091
2021-02-27 09:29:30,221 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice._onUploadProgress [842]: Upload _onUploadProgress bytes_total 399091
2021-02-27 09:29:30,229 - DEBUG - [MainThread] UM.Controller.setActiveStage [180]: Setting active stage to MonitorStage
2021-02-27 09:29:30,235 - DEBUG - [MainThread] UM.Controller.setActiveView [108]: Setting active view to SolidView
2021-02-27 09:29:30,247 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///C:/Program Files/Ultimaker Cura 4.8.0/plugins/PreviewStage/PreviewMenu.qml:25: TypeError: Cannot read property of null
2021-02-27 09:29:30,252 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///C:/Program Files/Ultimaker Cura 4.8.0/plugins/PreviewStage/PreviewMenu.qml:26: TypeError: Cannot read property of null
2021-02-27 09:29:30,380 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///C:/Program Files/Ultimaker Cura 4.8.0/resources/qml/RoundedRectangle.qml:68: TypeError: Cannot read property of null
2021-02-27 09:29:31,060 - INFO - [MainThread] SliceInfoPlugin.SliceInfo._onRequestFinished [284]: SliceInfo sent successfully
2021-02-27 09:29:34,549 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice._onUploadProgress [840]: Upload _onUploadProgress bytes_sent 0
2021-02-27 09:29:34,550 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice._onUploadProgress [842]: Upload _onUploadProgress bytes_total 0

Два места где происходит передача и она проскакивает мгновенно в одном случае, в другом вообще пытаемся передать 0 байт.

Попробуйте удалить файл лога, запустите Куру и попередавать файлы пару раз и приложите лог.

**Comment by Malderin** [comment]
> Попробуйте удалить файл лога, запустите Куру и попередавать файлы пару раз и приложите лог.

Сделал. Плагин версии 1.2.2 (обновился сегодня и маркета)
[cura.zip](https://github.com/Jeredian/mks-wifi-plugin/files/6372383/cura.zip)

**Comment by Elkin-Vasily** [comment]
Тааак:
DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevice.on_read [1012]: mks recv: M994 /NTITL~1.GCO;896262

А SD-карта у Вас какая? Штатная? Попробуйте с хорошей SD (из тех что не шли с чем-то китайским в комплекте).

**Comment by Malderin** [comment]
> А SD-карта у Вас какая? Штатная? Попробуйте с хорошей SD (из тех что не шли с чем-то китайским в комплекте).

Это было первое что я попробовал. Перепробовал все китайские что были, из нормальных были карты трансцендент и самсунг. Не меняется ничего.

**Comment by Elkin-Vasily** [comment]
Проблема еще актуальна?

**Comment by Malderin** [comment]
> Проблема еще актуальна?

К сожалению, да.

**Comment by Elkin-Vasily** [comment]
Скинете лог-файл с текущей версией плагина?

**Comment by Malderin** [comment]
> Скинете лог-файл с текущей версией плагина?
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/7403456/cura.log)

**Comment by Elkin-Vasily** [comment]
Хм, все так же. А какой версии у Вас Марлин и откуда? Каким образом подключены по WiFi к принтеру (напрямую или через роутер)?

**Comment by Malderin** [comment]
> Хм, все так же. А какой версии у Вас Марлин и откуда? Каким образом подключены по WiFi к принтеру (напрямую или через роутер)?

Марлин последний официальный из ветки багфикса (пробовал так же и стабильный). Кура 4.11 и 4.12, запускаю со стационарного ПК, подключенного к роутеру через кабель. Роутер ТП линк (поставил недавно) до этого был другой, netgear. Результат от смены роутера не меняется.
Не знаю в какой момент поломалась эта функция, я это как то упустил из виду, в чем причина неизвестно, увы.

**Comment by Elkin-Vasily** [comment]
Кроме нашего плагина еще какие-то стоят?

**Comment by Malderin** [comment]
да много всяких, в логе есть список в самом начале.

**Comment by Elkin-Vasily** [comment]
Подозреваю что кто-то из них ломает, других вариантов не вижу

**Comment by Malderin** [comment]
> Подозреваю что кто-то из них ломает, других вариантов не вижу

Снес все плагины, результат не изменился. Главное сама то передача работает, не работает именно отображение передачи.
Я не знаю что конкретно случилось, но могу предположить, что это могут быть какие то изменения в марлине, как известно там их много и в последнее время они там сильно сосредоточились на оптимизации и уменьшении (чистке) кода. Возможно какие то изменения поломали связь мкс вайфай плагина и марлина. В любом случае я бы написал о проблеме в ветке марлина, но не знаю что написать, нужна какая то конкретика а ее у меня нет.

**Comment by Elkin-Vasily** [comment]
У меня на одном из принтеров довольно свежий марлин и такой беды нет. Плюс по коду выходит что ломается сигнал от Qt-шного http-менеджера. Не уверен что это может быть что-то на стороне марлина. Ломается процесс получения прогресса передачи при post-запросе.

**Comment by Malderin** [comment]
Все работало какое то время назад и потом вдруг перестало. В чем причина так и не понятно. Я точно знаю что не менял ничего со своей стороны кроме версии самой куры, версии плагина мкс вайфай и постоянно изменяющихся версий прошивки марлин. Что конкретно поломало работу сказать не могу.

**Comment by Malderin** [comment]
Для теста поставил куру 4.6 и старую версию плагина 1.1.3. Результат не изменился. На версии куры 4.6 передача работала точно, я помню.

**Comment by Malderin** [comment]
Наша беседа навела на мысль. Я решил проверить установленные антивирусные программы.  Их у меня 2, это касперский тотал секьюрити и встроенный защитник виндовс (естествеено работает какая то одна). 
Отключил касперского,  включился защитник и тут же выдал предупреждение про куру, где я дал все возможные разрешения. И чудо, все заработало как надо. 
Включил касперского и опять индикатор передачи работать перестал. Короче говоря, непонятно почему, но в какой то момент мешать плагину нормльно работать стал касперский (к слову он стоял у меня давно, видимо какое то его обновление что то ужесточило и поломало работу плагина).
Дальше все просто. Открыл сетевые правила для куры в разделе "мониторинг сети/сетевая активность" (делается при запущенной куре), и на вкладке "исключения" поставил галку "не контролировать активность программы". 
Все работает, индикатор отображается, проценты показываются. 
Спсаибо за потраченнное время.
![1](https://user-images.githubusercontent.com/52313714/138586943-1cd226dc-df08-440e-83d7-7239a98ad808.jpg)

**Comment by Elkin-Vasily** [comment]
Здорово! Поздравляю
