### ISSUE TITLE
BUG? Cura and printer connection, connection procedure

### ISSUE THREAD

**Issue by Malderin** [Jeredian/mks-wifi-plugin#129]
Не соединяется Кура и принтер. 
Порядок такой:
1. Запускаем Куру
2. Включаем принтер 
3. Ждем
4. Соединения не происходит, на вкладке "Монитор" пусто, нет ни кнопок от плагина ни температур, ничего.

Для возможности и упрощения соединения в такой ситуации создал второй принтер (Эндер -2, выбрал из готовых). После выполнения вышеуказанных действий, переключаюсь на эндер 2 и сразу назад на свой принтер, плагин появляется, принтер обнаруживается и соединяется, вот демонстрация:
https://disk.yandex.ru/i/7E_vLEkCJcBJfw

Если изменить порядок и сперва включить принтер, потом запустить куру, то все подхватывается и соединияется.

The Cura and the printer are not connected.
The order is:

1. Launching Curu
2. Turn on the printer
3. We wait
4. The connection does not occur, the "Monitor" tab is empty, there are no buttons from the plugin, no temperatures, nothing.

For the possibility and simplification of the connection in such a situation, I created a second printer (Ender -2, I chose from the ready-made ones). After completing the above steps, I switch to Ender 2 and immediately back to my printer, the plugin appears, the printer is detected and connected, here is a demo:
https://disk.yandex.ru/i/7E_vLEkCJcBJfw

If you change the order and first turn on the printer, then start the kuru, then everything is picked up and connected.

**Comment by Elkin-Vasily** [comment]
Это известный баг, будет решен в рамках работы над #58

**Comment by Jeredian** [comment]
duplicate #58

**Comment by Jeredian** [comment]
Duplicate of #58
