### ISSUE TITLE
[BUG] Image setting is hidden before IP address added 

### ISSUE THREAD

**Issue by Jeredian** [Jeredian/mks-wifi-plugin#136]
At first open plugin settings, Image setting is hidden before IP address added.
This setting not related to IP address, so we should show it always.

**Comment by Elkin-Vasily** [comment]
To set up plugin version with newer UI you must to press "Manage Printers", than press "MKS WiFi Plugin", than set up needed settings like on screenshots below:

<img width="785" alt="Screenshot 2021-05-26 at 15 41 54" src="https://user-images.githubusercontent.com/812359/119661879-6c0aea00-be39-11eb-955a-7feb836a9c32.png">

<img width="784" alt="Screenshot 2021-05-26 at 15 42 01" src="https://user-images.githubusercontent.com/812359/119661895-7200cb00-be39-11eb-8c34-15ce31254b80.png">
