### ISSUE TITLE
TFT info (image) is not available

### ISSUE THREAD

**Issue by ColdBeer72** [Jeredian/mks-wifi-plugin#138]
Since last update (1.2.1) on march 10th, there is no TFT info (no image to show on TFT35 display) on the generated gcode file.

**Comment by Elkin-Vasily** [comment]
Go to "MKS WiFi Connection" settings and set your printer preview size. It turned off by default.

**Comment by ColdBeer72** [comment]
> Go to "MKS WiFi Connection" settings and set your printer preview size. It turned off by default.

My printer is not connected through WiFi, just through "human movement" (with the SD card), so I have no option to set my preview size. My motherboard is a Robin Nano V1.2 with TFT35 screen.

**Comment by Elkin-Vasily** [comment]
Just add random IP address, then you can set image size.

We have created issue to manage image size without adding IP (#136)

**Comment by ColdBeer72** [comment]
Fine! I used 127.0.0.1 (localhost) as IP address but, I suppose **simage** is "icon view" and **gimage** is "printing view". How do I know which is the correct one for Robin Nano V1.2?

**Comment by Elkin-Vasily** [comment]
Default wil be ok for you

**Comment by Boneunit** [comment]
Hi,
Thank you for your help but it doesn't work for me.
I don't think that it's a problem of printer settings, it comes from the curas output file which doesn't contain any image preview

**Comment by rdulak** [comment]
> 
> 
> Fine! I used 127.0.0.1 (localhost) as IP address but, I suppose **simage** is "icon view" and **gimage** is "printing view". How do I know which is the correct one for Robin Nano V1.2?

How did you add the ip address to an existing printer ?

**Comment by ColdBeer72** [comment]
> > Fine! I used 127.0.0.1 (localhost) as IP address but, I suppose **simage** is "icon view" and **gimage** is "printing view". How do I know which is the correct one for Robin Nano V1.2?
> 
> How did you add the ip address to an existing printer ?

In printer configuration, I don't have my computer at this moment, but you'll see something like "network config" in the selected printer.
