### ISSUE TITLE
Shorten file name automatically when it's too long

### ISSUE THREAD

**Issue by vahron** [Jeredian/mks-wifi-plugin#139]
Hey I often build my designs in Fusion360 and import them as STL to Cura.
Fusion360 builds filename as uuid for Cura, and it's a long filename. Each time I try to print it, Cura says "file name is too long, please rename file".

Is it possible for wifi plugin to actually shorten name automatically? It's quite annoying to have to type a new random name for every print.

**Comment by Jeredian** [comment]
done in #262
