### ISSUE TITLE
Uploading error [BUG]

### ISSUE THREAD

**Issue by kazakh1979** [Jeredian/mks-wifi-plugin#141]
Before the last update I had no issue with this plugin. But after the update of march 10th I get everytime "upload error" message.

**Comment by Jeredian** [comment]
@kazakh1979 , is it still actual for you?
If it is, please get to us more information, you can see it below. 

**Describe the bug**: clear and concise description of what the bug is.

**Reproduce Steps** :to reproduce the behavior:
Go to '...'
Click on '....'
Scroll down to '....'
See error

**Expected behavior**: clear and concise description of what you expected to happen.
**Screenshots**: If applicable, add screenshots to help explain your problem.
**Desktop configuration**:
OS: [e.g. Windows 10, macOS 11.1]
Cura version: [e.g. 4.8.0]
Plugin version: [e.g. 1.1.2]
3D printer: [e.g. FlyingBear Ghost 5]

**Comment by Elkin-Vasily** [comment]
Is this issue actual?

**Comment by Levingard** [comment]
I have exatly the same problem. I can connect to Printer via wifi, move axis, monitor prints, but when i try to send the printjob via wifi, the upload window disappears and the printer says uploading error.

Printer: Flying Bear Ghost 5 with actual firmware and Cura 4.9.1 with Plugin 1.2.2

**Comment by Markosyan-AR** [comment]
The same issue with flying bear ghost 5 + cura 4.9.0 + 1.2.2 plugin. Failed to upload large files.
Printer Firmware- [https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)
Is it possible to collect tracing info or logs or something like that?

**Comment by idlesign** [comment]
**Updated.**
I was able to reproduce it on Ghost 5 & Cura 4.11.0, plugin 1.2.4 without SD card: sending model with wi-fi leads to Uploading error on display. With SD card **works as expected** though.

**Comment by Elkin-Vasily** [comment]
> **Updated.**
> 
> I was able to reproduce it on Ghost 5 & Cura 4.11.0, plugin 1.2.4 without SD card: sending model with wi-fi leads to Uploading error on display. With SD card **works as expected** though.
> 
> 

WiFi module saves files on SD and then start printing. Without SD it won't work.

**Comment by Elkin-Vasily** [comment]
> The same issue with flying bear ghost 5 + cura 4.9.0 + 1.2.2 plugin. Failed to upload large files.
> 
> Printer Firmware- [https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)
> 
> Is it possible to collect tracing info or logs or something like that?

Try to turn printer on without SD, then insert SD, than start Cura and try to print.

**Comment by Elkin-Vasily** [comment]
> I have exatly the same problem. I can connect to Printer via wifi, move axis, monitor prints, but when i try to send the printjob via wifi, the upload window disappears and the printer says uploading error.
> 
> 
> 
> Printer: Flying Bear Ghost 5 with actual firmware and Cura 4.9.1 with Plugin 1.2.2

Have you tried to use another SD card?

**Comment by Elkin-Vasily** [comment]
closed due to inacktivity
