### ISSUE TITLE
[BUG] MKS Marlin 2.0 - Plugin 'develop' and 1.1.2 do not render preview in Cura 4.8.0

### ISSUE THREAD

**Issue by martinbogo** [Jeredian/mks-wifi-plugin#142]
**Describe the bug**

After installing the MKS WiFi plugin in Cura 4.8.0 on Windows 10... I see the "Save as TFT" option, however the file that is produced lacks the simage; image preview... only the gcode is output.

**To Reproduce**
1. Download Cura 4.8.0
2. Clone the mks-wifi-plugin repo from https://github.com/Jeredian/mks-wifi-plugin
3. Slice calibration cube or any other stl file with standard settings
4. Select "Save as TFT" from the dialog to the local disk or SD card
5. Open the resulting .gcode file, and there is no image preview

**Expected behavior**

The beginning of the file should contain an image preview rendered as a series of simage; lines which are rendered by the MKS TFT35 LittleVGL interface in Marlin 2.0. 

**Desktop (please complete the following information):**
 - OS: Windows 10, MacOS Big Sur Beta 4
 - Cura version: 4.8.0
 - Plugin version: both develop branch, and 1.1.2
 - 3D printer: FOKOOS Odin 5-F3
 - MKS Robin Nano v1.2

**Comment by Boneunit** [comment]
Hi,
I have exactly the same problem. It works sometime but in most case their is no preview picture.

**Comment by Elkin-Vasily** [comment]
Hi, in the latest version of plugin preview image is set to "None" by default.
You need to add some (any) IP to printer, and set "simage" and "gimage" options to yours TFT screen (if you don't now what it is most likely "Default" will be ok for you).

**Comment by Elkin-Vasily** [comment]
duplicates #138

**Comment by Boneunit** [comment]
Hi,
Thank you for your help but it doesn't work for me.
I don't think that it's a problem of printer settings, it comes from the curas output file which doesn't contain any image preview

**Comment by ColdBeer72** [comment]
It worked for me, just adding an IP (127.0.0.1, which is localhost) to one of your printers in Cura. You don't need to add IP to the rest of your real or virtual printers. After that, every "TFT/gcode" file has the image inside.

**Comment by Elkin-Vasily** [comment]
> Hi,
> 
> Thank you for your help but it doesn't work for me.
> 
> I don't think that it's a problem of printer settings, it comes from the curas output file which doesn't contain any image preview

Do you have some another plugins installed? For example Arc Welder can cause this issue.

**Comment by Boneunit** [comment]
Hi,
I have uninstalled all the plugins and it's still the same thing no image preview in the GCode.

**Comment by Elkin-Vasily** [comment]
Could you download here a log file? It can be found:

• Windows: %APPDATA%\cura<Cura version>\cura.log , or C:\Users\\AppData\Roaming\cura<Cura version>\cura.log
• OSX: $USER/Library/Application Support/cura//cura.log
• Linux: $USER/.local/share/cura//cura.log

**Comment by Boneunit** [comment]
Here is the log file :
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/6215127/cura.log)

**Comment by Boneunit** [comment]
Hi,
Any idea ?

**Comment by Jeredian** [comment]
Hi, @Boneunit . Is it still actual for you?

Can you try the following steps:
1. Open printer settings
2. Go to the plugin settings window
3. Press to the "image settings" button
4. Change if a selection of image preset to the "Base" or "Custom" with `simage: 100, gimage: 100`
5. Save these settings
6. Check plugins settings window there should be current simage, gimage values
7. Try to save the file by "Save as TFT" which is provided from our plugin, or send it via WIFI.

If it doesn't help please attach log, stl model, and gcode file and screenshot of your plugins settings window. I will try to reproduce and check it.

**Comment by Boneunit** [comment]
Hi,
Thanks for your answer. I have'nt the plugin "image settings button" in my printer settings. I only have "MKS wifi connection" button

**Comment by Jeredian** [comment]
@Boneunit , you are right, you need to press on "MKS wifi connection", after that you will see plugin settings window and "image settings" button. Please, take a look at the step-by-step screenshoots:
1. Press to the "MKS wifi connection" button
![image](https://user-images.githubusercontent.com/9591166/115955245-1a033b80-a4fe-11eb-923e-0417823cc925.png)
2. Press to the image settings" button
![image](https://user-images.githubusercontent.com/9591166/115955277-31dabf80-a4fe-11eb-973b-6258e50a9dde.png)
3. Select default image preview setup and save it by clicking "ok" button.
![image](https://user-images.githubusercontent.com/9591166/115955283-46b75300-a4fe-11eb-9c2c-423752243d9c.png)
4. After it you will see that settings saved
![image](https://user-images.githubusercontent.com/9591166/115955360-a6adf980-a4fe-11eb-94a6-4386d15b1130.png)
5. Close plugin settings window.
6. Test with some random 3d model...

Hope it will helps to you

**Comment by Boneunit** [comment]
Thanks a lot for your help. I have done each step but it's still the same 
![24 194206](https://user-images.githubusercontent.com/78499840/115967850-34a4d700-a535-11eb-944c-7b81822909ea.png)

**Comment by Jeredian** [comment]
@Boneunit , can you attach gcode file and log with saving it? I'll check it...

**Comment by Boneunit** [comment]
Here are the log file and the gcode file:
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/6371316/cura.log)
[Untitled.gcode.txt](https://github.com/Jeredian/mks-wifi-plugin/files/6371317/Untitled.gcode.txt)

**Comment by Elkin-Vasily** [comment]
> Here is the log file :
> [cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/6215127/cura.log)

In your log I see this:
DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevicePlugin.reCheckConnections [149]: GlobalContainerStack change None

It is some strange behaviour... Try to delete your printer from Cura and add it once more.

**Comment by Elkin-Vasily** [comment]
> Here are the log file and the gcode file:
> [cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/6371316/cura.log)
> [Untitled.gcode.txt](https://github.com/Jeredian/mks-wifi-plugin/files/6371317/Untitled.gcode.txt)

In this log you have:
DEBUG - [MainThread] MKSWifiPlugin.__matchVersion [56]: This version of MKS WiFi Plugin is not compatible with current version of Cura. Please check for an update.

**Comment by Jeredian** [comment]
@Boneunit , if you are using Cura 4.9.0 at now, I'd suggest to manually update the plugin to 1.2.2 RC1 ( https://github.com/Jeredian/mks-wifi-plugin/releases/tag/1.2.2-dev )

**Comment by Boneunit** [comment]
I have done the update with the new version 1.2.2 and it's still the same

**Comment by Elkin-Vasily** [comment]
Please attach log file with latest plugin version installed

**Comment by Ryszard-wpl** [comment]
I have the same problem. In Cura 4.9.0
In step 3 of your guide - I cannot select any options - all are grey and inactive. Plugin is connected to printer and there is MKS TFT35. 
![Zrzut ekranu 2021-04-26 o 01 06 31](https://user-images.githubusercontent.com/81155959/116012595-b0814b00-a62b-11eb-94ac-92af2c5adbfa.jpg)


I restore version 4.8.0. of Cura and all works OK. Options are not grey and I can select image size.

**Comment by Boneunit** [comment]
Here is the log file 
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/6374418/cura.log)

**Comment by Jeredian** [comment]
@Ryszard-wpl , it's another issue, I created a ticket for it #163. And we will try to solve it ASAP.

**Comment by Jeredian** [comment]
@Boneunit, thanks for sending the new log file, but it seems that you save the file by using the default Cura saving. 
Can you send to us a screenshot of which button do you use to save the gcode file?

**Comment by Boneunit** [comment]
This is this button 
![image](https://user-images.githubusercontent.com/78499840/116078967-8e251700-a697-11eb-837f-2a0ad378c738.png)

**Comment by Elkin-Vasily** [comment]
> This is this button 
> 
> ![image](https://user-images.githubusercontent.com/78499840/116078967-8e251700-a697-11eb-837f-2a0ad378c738.png)
> 
> 

Do you have any other plugins installed?

**Comment by Boneunit** [comment]
Hi,
Here is the plugin list : 
![image](https://user-images.githubusercontent.com/78499840/119935633-1b55d700-bf88-11eb-8343-d13596deb8a7.png)

**Comment by Boneunit** [comment]
Hi,
I have installed the 1.2.4 and it's still the same.

**Comment by Jeredian** [comment]
Hi, @Boneunit, 
can you attach, please, the latest log file, with a full process ( loading cura, slice file, save it with our plugin)?
And as I saw, it seems we forgot to ask about your printer model...
What happens if you send a file via WIFI  to the printer?

**Comment by Boneunit** [comment]
Hi,
Here is the log file :
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/7071844/cura.log)
My printer is a Ender 3.
I don't have the wifi on my printer

**Comment by Jeredian** [comment]
@Boneunit , 
Hi, I just back from vacation and checked your file.
Maybe there can be some issue with the slicing process and somehow plugin doesn't encapsulate this. (stuff like on 1272 line),  but the chance of it is low.

Have you tried to re-check the "screenshot support" settings? it seems that we have an issue with correct saving these settings, and for some users, it switched back to disabled or default. It should be like this (`both checkboxes should be in a checked state`) :
![image](https://user-images.githubusercontent.com/9591166/132834138-276bbecf-dfc3-4ed2-9831-8b9d82a377e8.png)

Also, can you try to select custom settings, and re-select the default one? I know it looks ridiculous but if we don't have any error about saving, there should be something wrong with the settings parameter.

**Comment by Jeredian** [comment]
@Boneunit, 
I added extra logs for file saving, can you try to use the latest version from the `develop` branch, please, and send a new `cura.log` file?
Btw, you can try Cura 4.11, a plugin from the `develop` branch compatible with it.

**Comment by Elkin-Vasily** [comment]
@Boneunit is this issue actual for you?

**Comment by Elkin-Vasily** [comment]
closed due to inacktivity
