### ISSUE TITLE
[BUG] Printer reboot on plugin connexion

### ISSUE THREAD

**Issue by Dtcreation** [Jeredian/mks-wifi-plugin#143]
**Describe the bug**
My printer reboot each time the plugin connect to the printer (Cura 4.8)

**To Reproduce**
1. Start a print
2. The printer reboot

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Cura version: 4.8.0
 - Plugin version: 1.2.1
 - 3D printer: Wanhao D12
 - Motherboard and/or WiFi module firmware version: MKS Nano Robin 35 + MKS Wifi

**Additional context**

**Comment by Elkin-Vasily** [comment]
Can you specify mainboard and WiFi module firmware?

**Comment by Dtcreation** [comment]
MKS Robin Nano V1.2
![DSCN1706](https://user-images.githubusercontent.com/60579620/112131256-ace04b80-8bc9-11eb-91c4-66799b2a0f00.JPG)

**Comment by Elkin-Vasily** [comment]
It is a hardware version. And what about firmware?

**Comment by Elkin-Vasily** [comment]
Is this issue actual?
