### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by X-Dron** [Jeredian/mks-wifi-plugin#144]
**Describe the bug**
Don't work in Ultimaker Cura Arachne_engine_beta 99.9.1

**To Reproduce**
Install Cura Arachne_engine_beta 99.9.1
Check printer settinngs

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7,]
 - Cura version: [e.g. Cura Arachne_engine_beta 99.9.1]
 - Plugin version: [e.g. 1.2.1]
 - 3D printer: [e.g. FlyingBear Ghost 4S]
 - Motherboard and/or WiFi module firmware version: [Marlin 2.0.7.2]
![28-03-2021 20-26-51](https://user-images.githubusercontent.com/10565667/112761468-2762fe00-9004-11eb-934e-91f69ae5711a.png)

**Comment by X-Dron** [comment]
fix in __init__.py
    if cura_version == "Arachne_engine_alpha" or cura_version == "Arachne_engine_beta":

**Comment by Elkin-Vasily** [comment]
Hi, just get latest commit from develop it was fixed already.
