### ISSUE TITLE
[Question] Hot can I get data from 3d Printer

### ISSUE THREAD

**Issue by valeriofantozzi** [Jeredian/mks-wifi-plugin#146]
Hy, I would like to access the monitor data of my FlyingBear Ghost 5 while running.
The plugin works perfectly in Cura but I would like to write a simple python script that works outside of Cura and take the same monitor data. 

Can you help me? :)

**Comment by Elkin-Vasily** [comment]
Hmmm, do you want to write it from the scratch or take our plugin as a base? I think the best way is the first. If you agree, here is MKS-WIFI protocol: https://github.com/makerbase-mks/MKS-WIFI/blob/master/Transfer%20protocal%20%20between%20ESP%20and%20MCU.docx

Is it that you need?

**Comment by valeriofantozzi** [comment]
I was wondering if there's someone with an example code from where to start.
And yes, the MKS-WIFI protocol is the right way to make it, thanks.
