### ISSUE TITLE
[FEATURE] Console View

### ISSUE THREAD

**Issue by daniel-scatigno** [Jeredian/mks-wifi-plugin#169]
There is a Input Box for sending Gcode commands, but we can't see any results when it's related to info, Like checking debug information about TMC Drivers or checking endstops state (M119). It would be great to have a console for sending commands and receiving information

**Comment by Elkin-Vasily** [comment]
We are using Cura's monitor tab to add our elements there, and there is no console view.

You can see the answers from WiFi module in cura.log file.

But remember, that this answers are not from mainboard, they are from WiFi module.
