### ISSUE TITLE
[FEATURE] Change max file name length from settings

### ISSUE THREAD

**Issue by Jeredian** [Jeredian/mks-wifi-plugin#172]
Some users asked about features, to control file name length.
There is a few printer's firmware can use only file lower than 10 symbols, but this is not the whole printers that we have.
We can place this param to the settings, and make it by default equal to 10, if someone needs a longer file name  they will be able to change these settings

**Comment by Elkin-Vasily** [comment]
Now added a text field for maximum file name length.

![Screenshot 2021-08-04 at 18 23 15](https://user-images.githubusercontent.com/812359/128208251-e5f8aa7c-f1df-4f70-b83e-f6cf0f60cc70.png)
