### ISSUE TITLE
does not work in Cura 4.10.0

### ISSUE THREAD

**Issue by Ignat-8** [Jeredian/mks-wifi-plugin#173]
Hello, this plugin does not work in Cura 4.10.0

**Comment by metjuzlyapar** [comment]
i have encounted the same issue in Cura 4.10

**Comment by Jeredian** [comment]
It should not because the max supported version is 4.9.0. Support of 4.10 will be at the start of the next week in dev branch. #171

**Comment by Jeredian** [comment]
Duplicate of #171
