### ISSUE TITLE
Dont work with cura 4.10.0 [BUG]

### ISSUE THREAD

**Issue by TimeJammer** [Jeredian/mks-wifi-plugin#174]
Dont work with cura 4.10.0

Manuel or cura market.

**Comment by Gimran** [comment]
same

**Comment by commo81** [comment]
Same thing here. Installed from marketplace and manually, "cannot communicate with printer at IP address." I've only had it successfully work on Cura 4.2.1 so I'm using that for now.

**Comment by Jeredian** [comment]
Duplicate of #171

**Comment by Jeredian** [comment]
Please check the already exited issues, before creating a new one.

**Comment by emare62** [comment]
I have checked the issue #171but did not understand what to do to fix this.
After some tests I edited file plugin.json :
 ```
old     "maximum_cura_version": "4.9"
new     "maximum_cura_version": "4.10"
```
now seems to work

**Comment by Jeredian** [comment]
You also need to change these lines:
```
  "supported_sdk_versions": [
      "7.1.0",
      "7.2.0",
      "7.3.0",
      "7.4.0",
      "7.5.0"
  ]
```
after that, it will be shown, but if there are some breaking changes it would not work and you'll need to check the cura.log file

**Comment by Jeredian** [comment]
I'll start working on #171 today, after work. So tomorrow there will be an update in the dev branch.

**Comment by TimeJammer** [comment]
Thanks for your answers and hard work. Good luck with.

**Comment by TimeJammer** [comment]
> I have checked the issue #171but did not understand what to do to fix this.
> After some tests I edited file plugin.json :
> 
> ```
> old     "maximum_cura_version": "4.9"
> new     "maximum_cura_version": "4.10"
> ```
> 
> now seems to work

emare62, Thanx for fix. 
It's seems working for me too...
At least it works for now. Thanks!
