### ISSUE TITLE
Doesent work with cura 4.10

### ISSUE THREAD

**Issue by EgorIII** [Jeredian/mks-wifi-plugin#177]
There is no "mks wifi connection" button on Cura 4.10, but plugin is installed and enabled.
works correctly on older versions 

 - OS: Windows 10
 - Cura version: 4.10
 - Plugin version: 1.2.2
 - 3D printer: FlyingBear Ghost 4S

**Comment by aperoap1** [comment]
You can download the current version: [https://github.com/Jeredian/mks-wifi-plugin](https://github.com/Jeredian/mks-wifi-plugin)
Then open cura -> help -> show configuration folder 
(C:\Users\surface3\AppData\Roaming\cura\4.10\plugins\MKSWifiPlugin\MKSWifiPlugin)

Unzip the downloaded zip file and copy everything in there (replace data). Then restart cura.
It worked for me.

**Comment by diviatrix** [comment]
Sadly it wont connect
https://i.imgur.com/CfD04R8.png

**Comment by Jeredian** [comment]
@diviatrix , it seems that you need to add an IP address of your printer. You can't connect if there is nothing to.

**Comment by diviatrix** [comment]
@Jeredian it is actually added, and this is what it looks like :)

**Comment by Jeredian** [comment]
@diviatrix, please create a separate issue about it, we will investigate this. Because on my mac and pc it works as it should. 
Have you tried to toggle the wifi support checkbox and add your IP address again?

**Comment by marsaldev** [comment]
Same here, no button for configuration:

- OS: macOS Big Sur 11.4
- Cura version: 4.10
- Plugin version: 1.2.2 (latest)
- 3D printer: FlyingBear Ghost 5

<img width="622" alt="Schermata 2021-07-30 alle 11 00 52" src="https://user-images.githubusercontent.com/48283112/127629319-3755995f-3287-4b2f-b776-af05019cdbda.png">

<img width="780" alt="Schermata 2021-07-30 alle 11 01 52" src="https://user-images.githubusercontent.com/48283112/127629330-eff56b8d-60db-47a7-835c-78dc5b49ffcc.png">

**Comment by Jeredian** [comment]
@marsaldev  , please read comments, and take a look at the pinned issues that are already done, before comment :-)

https://github.com/Jeredian/mks-wifi-plugin/issues/177#issuecomment-884512417

For now, you can use the version from dev. branch, next release will be at the start of August

**Comment by marsaldev** [comment]
@Jeredian Thanks a lot, I've tried the stable release instead the dev, sorry my bad.

**Comment by Pumpken** [comment]
Developer version adds the button but still cant connect. Same as @diviatrix. But its nice to know that the DEV is on it.

**Comment by Jeredian** [comment]
@Pumpken, @diviatrix can you tell, please, your os version. maybe I will try to fix it this weekend. And it will be great if someones can show a gif or video (screencast) that describes your actions because we can fix only what we can reproduce.

**Comment by Jeredian** [comment]
@Pumpken , @diviatrix , btw after update to the current develop version, you need to set your settings like it's the first time.
So it looks like a conflict of version with previous settings. You can try to clear the plugin folder and copy it from develop, maybe it can fix this. (because when Cura updates a plugin it does the same thing)

**Comment by Jeredian** [comment]
closed due inactivity
