### ISSUE TITLE
[BUG]Help text either flickers or obscures Extruder 1 temperature information

### ISSUE THREAD

**Issue by bellzw** [Jeredian/mks-wifi-plugin#179]
**Describe the bug**
When hovering over the Extruder 1 temperature information, the help text flickers over the temperature input box and Pre-heat button.  When  hovering over Extruder 2's temperature input box or Pre-heat button, and the mouse is moved horizontally left over Extruder 1's Pre-heat button or temperature input box, the help text hides Extruder 1's Pre-heat temperature button and temperature input box.  Both of these make it difficult or impossible to click the Pre-heat button and set a temperature to which to preheat.

**To Reproduce**
1. Connect to BIBO 2 dual printer
2. Go to Monitor page
3. Hover over Extruder 1 Pre-heat button or the temperature input box.
4. Observe the error
5. Hover over Extruder 2 Pre-heat button or temperature input box
6. Move the mouse horizontally over Extruder 1's Pre-heat button or temperature input box
7. See the help text cover Extruder 1's Pre-heat button and temperature input box

**Expected behavior**
Help text should appear further to the left so as not to cover the Pre-heat button or temperature input box

**Screenshots**
![help](https://user-images.githubusercontent.com/51066449/126856771-328f1e73-1a6d-41fd-b9a4-25e1a9a4b7e4.png)
If I hover over Extruder 2's input box or Pre-heat button, and then move horizontally left, the help text box covers Extruder 2's temperature input box and the Pre-heat button.

This MP4 lets you see the flickering of the help box when the mouse hovers over the Pre-heat button or temperature input box.
https://user-images.githubusercontent.com/51066449/126856928-19eae938-1373-4821-945e-74a699e450f9.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit on a Lenovo Yoga 14
 - Cura version: 4.9.1
 - Plugin version: 1.2.2
 - 3D printer: BIBO 2 dual
 - Motherboard and/or WiFi module firmware version: 3.03

**Additional context**

**Comment by Elkin-Vasily** [comment]
Can you try to reproduce this bug with the plugin version from devel branch?
