### ISSUE TITLE
Cura interface layout overlap

### ISSUE THREAD

**Issue by adripo** [Jeredian/mks-wifi-plugin#19]
Sorry for opening another bug, but I want to keep things separated.

I have a bug in the layout of the plugin on cura 4.4.1
Here's a screenshot:
<details>

![2020-05-30_02-09-54-738_Cura](https://user-images.githubusercontent.com/26493496/83314476-df741e80-a21a-11ea-81fd-008c1607c6a2.png)
</details>

Some of the buttons are overlapping in the Printer control and Active print sections.
Thanks

**Comment by ravetam** [comment]
MonitorItem4x.qml

Changing the y from 450 to 600 seems to fix the issue

```
Row
            {
                x:10
                y:600
                spacing: 10
                anchors
                {
                    leftMargin: UM.Theme.getSize("default_margin").width
                    rightMargin: UM.Theme.getSize("default_margin").width
                    horizontalCenter: parent.horizontalCenter
                    // bottomMargin: UM.Theme.getSize("default_margin").height
                }
                Button
                {
                    id: homebutton2
                    height: UM.Theme.getSize("save_button_save_to_button").height
                    // text: catalog.i18nc("@label", "Fan ON");
                    text: currentLanguage == "zh_CN" ? "打开风扇" : "Open Fan"
                    onClicked: Cura.MachineManager.printerOutputDevices[0].openfan()
```

**Comment by PigeonFX** [comment]
> MonitorItem4x.qml
> 
> Changing the y from 450 to 600 seems to fix the issue
> 
> ```
> Row
>             {
>                 x:10
>                 y:600
>                 spacing: 10
>                 anchors
>                 {
>                     leftMargin: UM.Theme.getSize("default_margin").width
>                     rightMargin: UM.Theme.getSize("default_margin").width
>                     horizontalCenter: parent.horizontalCenter
>                     // bottomMargin: UM.Theme.getSize("default_margin").height
>                 }
>                 Button
>                 {
>                     id: homebutton2
>                     height: UM.Theme.getSize("save_button_save_to_button").height
>                     // text: catalog.i18nc("@label", "Fan ON");
>                     text: currentLanguage == "zh_CN" ? "打开风扇" : "Open Fan"
>                     onClicked: Cura.MachineManager.printerOutputDevices[0].openfan()
> ```

This doesn't fix the 2 Extrude buttons being ontop of the Z-axis buttons.

**Comment by PigeonFX** [comment]
Seems change the following lines in MonitorItem4x.qml fixes the extruder buttons:

504: x:310
505: y:243
