### ISSUE TITLE
Plugin doesn't work via wifi with multiple istances of cura

### ISSUE THREAD

**Issue by adripo** [Jeredian/mks-wifi-plugin#20]
I tried to open different istances of cura with different objects to print, but only the first instance is connected via wifi with the printer. All the others doesn't.
If I go to MKS WIFI and try to connect manually via wifi nothing happens. The "connect" button remains clickable, but there is no message.
After that, if I close the working instance, none will work anymore. Even if I close them all and open just one window of cura. I have to open and close cura multiple times until it starts working again.
Is there any way to see a log? Or even a simple error message?
Thanks

**Comment by Elkin-Vasily** [comment]
Look at Cura log file, all plugins are logging their activities there

**Comment by Elkin-Vasily** [comment]
MKS WIFI module supports only one connection at a time.
