### ISSUE TITLE
Release 1.2.4 not working with Cura 4.11[BUG]

### ISSUE THREAD

**Issue by FabioMC** [Jeredian/mks-wifi-plugin#200]
Just installed Cura 4.11 and MKS Wifi Plugin stop working. Still works on Cura 4.10.

**Comment by SDenis8** [comment]
Goto C:\Users\@YOURUSERNAME@\AppData\Roaming\cura\4.11\plugins\MKSWifiPlugin\MKSWifiPlugin
(or click in Cura "Help"->"Show configuration folder")

Edit plugin.json
**from** "maximum_cura_version": "**4.10.0**"
**to** "maximum_cura_version": "**4.11.0**"
Also you can set for feature something like that: 4.9999.0 :))

**Comment by FabioMC** [comment]
Thanks. It's working again.

**Comment by Jeredian** [comment]
@SDenis8 , @FabioMC,  thanks for the activity  :-)
FYI, Plugin compatibility was fixed in #197, and it's already in the develop branch. So plugin.json, will be updating mostly for SDK changes (as it should, because it may break something)
