### ISSUE TITLE
No creation/modification date of gcode files

### ISSUE THREAD

**Issue by adripo** [Jeredian/mks-wifi-plugin#21]
The gcode files uploaded via wifi have no modification date or creation date.
<details>

![2020-05-30_02-38-47-418_firefox](https://user-images.githubusercontent.com/26493496/83315228-ba81aa80-a21e-11ea-9b70-06a3d1cf4b13.png)
</details>

Is this something that can be fixed through the plugin or something related to the firmware?

Thank you

**Comment by Elkin-Vasily** [comment]
There is no way to transfer creation and modification date of the file via wifi at the moment. It is related with MKS WiFi module firmware (https://github.com/makerbase-mks/MKS-WIFI)
