### ISSUE TITLE
If the name of the transferred file contains Chinese, it may result in the failure to start printing. It is recommended that you can prompt to rename before transferring

### ISSUE THREAD

**Issue by wqh227** [Jeredian/mks-wifi-plugin#23]
If the name of the transferred file contains Chinese, it may result in the failure to start printing. It is recommended that you can prompt to rename before transferring
如果傳送文件名稱包含中文，則可能導致無法開始打印，建議傳送前可以提示重命名

**Comment by zhpt** [comment]
You can update the latest firmware to fix it by https://github.com/makerbase-mks/MKS-Robin-Nano/tree/master/Nano%20firmware%20v2.x.x
