### ISSUE TITLE
MKS WiFi - CURA 4.12

### ISSUE THREAD

**Issue by 1lug1998** [Jeredian/mks-wifi-plugin#234]
### Plugin Version

1.2.5

### Cura Version

4.12

### Platform

Windows 11

### Printer

FLSun Cube with SKR 2 Mainboard

### Reproduction steps

I'm seeing some issues with the MKS wifi plugin and CURA 4.12.
The file shows that it uploaded successfully both in CURA and on the MKS TFT32 V3.0 I have. I cannot see the file on the screen. If I view the SD card in cura, it does not show the file. When I remove the SD card from the screen and plug it into my PC, I see the file name with no file extension, almost as if it did not upload as .gcode.

Any ideas?

### Actual results

There is not printable file on the SD card. 

### Expected results

I expected a printable .gcode file on the SD card. 

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

Log file attached. 
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/7571542/cura.log)

**Comment by Elkin-Vasily** [comment]
Attach a log-file, please

**Comment by 1lug1998** [comment]
> 

I'm not quite sure how to get a log file of the issue.

**Comment by 1lug1998** [comment]
> Attach a log-file, please

Log file has been uploaded.

**Comment by Elkin-Vasily** [comment]
In the log file you have send I see that you try to upload 20mm_cube.gcode file, it works ok. And then I see this file in file list on your SD:

mks recv: Begin file list
mks recv: System Volume Information.DIR
mks recv: four_square_cons.gcode
mks recv: 4132-M-052REVB.gcode
mks recv: 20mm_cube.gcode
mks recv: End file list

Was there some problems with this file?

**Comment by 1lug1998** [comment]
> In the log file you have send I see that you try to upload 20mm_cube.gcode file, it works ok. And then I see this file in file list on your SD:
> 
> mks recv: Begin file list mks recv: System Volume Information.DIR mks recv: four_square_cons.gcode mks recv: 4132-M-052REVB.gcode mks recv: 20mm_cube.gcode mks recv: End file list
> 
> Was there some problems with this file?

20mm_cube uploaded just fine weirdly, I haven't had a good upload in a while. The others I put on the SD card by inserting the SD card into my PC to transfer them.

**Comment by Elkin-Vasily** [comment]
Ok, could you provide a log file with the unsuccessful file transfer?
