### ISSUE TITLE
GUI for the Monitor tab is jacked up 

### ISSUE THREAD

**Issue by PigeonFX** [Jeredian/mks-wifi-plugin#24]
Have overlapping buttons on the Monitor tab

![Screenshot (41)](https://user-images.githubusercontent.com/39096995/86259720-46874900-bbb4-11ea-94ce-ae5f0e1dd304.png)

**Comment by Jeredian** [comment]
Hi, @PigeonFX, I think we can close this issue because you fixed it.
But I have a little question about the way that you change UI. It was directly inside code, or you used Qt Designer for that?

**Comment by PigeonFX** [comment]
Just changed in the codes as a quick fix so I could use it.
