### ISSUE TITLE
Save as .TFT File not available

### ISSUE THREAD

**Issue by Filmman586** [Jeredian/mks-wifi-plugin#240]
### Plugin Version

1.26

### Cura Version

4.12.1

### Platform

Windows 10

### Printer

Elegoo Neptune 2

### Reproduction steps

I updated to 1.2.6 from the marketplace and the options is no longer available in Cura

### Actual results

![image](https://user-images.githubusercontent.com/83276762/143683502-570a0cba-2643-4bb5-8d85-5169bac039be.png)

### Expected results

Expected to see the save as .TFT option

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/7611787/cura.log)

**Comment by Elkin-Vasily** [comment]
From this version preview image (if this option is on for the currently selected printer) adds to the default "Save to Disk" option.

**Comment by Filmman586** [comment]
Thank You!
