### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by Cadoudal** [Jeredian/mks-wifi-plugin#246]
### Plugin Version

1.2.6

### Cura Version

4.11.0

### Platform

Windows 11

### Printer

Wanaho D12/230

### Reproduction steps

1. Install MKS-Wi-fi-plugin in Cura
2. Connect my Wanaho D12/230 to the wifi
3. Launch print via MKS-wifi-plugin in Cura
4. Go in 'Monitor' tab in Cura

### Actual results

Their is an issue with the display:
 - All the information under 'Send G-code' are mixed-up:
 
![image](https://user-images.githubusercontent.com/87127633/143898109-8f51c684-9715-4403-8d05-1975fc2b0185.png)

### Expected results

I would expect all the informations to be displayed properly

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by Elkin-Vasily** [comment]
This section is not related to the plugin, it is related to the Cura itself (you can check this - just connect your printer to the Cura with the USB cable). This section looks well with the higher resolution screens.

If you want - you can create issue in the Cura repository https://github.com/Ultimaker/Cura
