### ISSUE TITLE
Plugin when installed via the Marketplace doesn't work. 

### ISSUE THREAD

**Issue by PigeonFX** [Jeredian/mks-wifi-plugin#25]
If I install via the Marketplace it can't find my printer via IP, but if I manually install the plug-in it works fine (apart from the monitor layout being jacked up). 

Using PC and Cura 4.6.1 with a Makerbase MKS Robin WIFI ESP8266 WIFI module

**Comment by Jeredian** [comment]
Hi, are you tried the last version from the master branch?
I not updated plugin for Cura 4.6.* because they have too many bugs in the new version, and also changes at API version, so maybe it related to that thing. I planned to update the plugin at Marketplace at the start of August.

**Comment by dgorbunov** [comment]
This happens to me as well, plugin from Marketplace doesn't work.

**Comment by Emphantom4d** [comment]
Hey . I also installed it from the market, it does not work. install from github, does not work either.
what could be?
cura 4.6.2

**Comment by Jeredian** [comment]
Hi, can you try to use the latest version from the master branch?
I hope I'll update it on Market Place at this weekend, but if someones want to test before it, it will be helpful.
