### ISSUE TITLE
Wrong printing time

### ISSUE THREAD

**Issue by MrRefactoring** [Jeredian/mks-wifi-plugin#258]
### Plugin Version

1.2.6

### Cura Version

4.12.1

### Platform

Windows 10, MacOS 12

### Printer

Flying Bear Ghost 5

### Reproduction steps

1. Send printing job to the printer
2. Wait until the progress bar sets the value to 1%
3. Get a wrong printing time (4 or 5 hours displayed but printing just started)

### Actual results

Wrong printing time displayed

### Expected results

Showing correct printing time

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/10329528/146678837-046426ac-c01d-4bea-bb1b-4571493cf9d3.png)
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/7740988/cura.log)

My assumption is incorrect Python data parsing. But it's just assumption :)

**Comment by Elkin-Vasily** [comment]
By "Printing time" Cura means "Total printing time" and we updating self._time_total of Cura. The form on the monitor tab is mostly a Cura-form. So if you want, you can create an issue in the Ultimaker repo: https://github.com/Ultimaker/Cura
