### ISSUE TITLE
Printing not finish

### ISSUE THREAD

**Issue by feivur** [Jeredian/mks-wifi-plugin#259]
### Plugin Version

1.2.6

### Cura Version

4.11.0

### Platform

Windows 10

### Printer

FBG5

### Reproduction steps

After printing is complete, the plug-in remains in the "printing ..." state. It is not possible to stop printing, nothing happens after "Abort print" -> Yes. Have to restart the printer and cura.

### Actual results

After print finishes, plugin freezes

### Expected results

After print finishes, able to start new one

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/12371350/147088883-fc0c4e08-dbe8-4d6e-82fe-52a2fe6e203e.png)

**Comment by Jeredian** [comment]
@feivur , please attach the cura.log file.

**Comment by Elkin-Vasily** [comment]
What printer firmware do you use?

**Comment by feivur** [comment]
[cura.log.txt](https://github.com/Jeredian/mks-wifi-plugin/files/7774014/cura.log.txt)
Чтобы плагин одумался, приходится переподключать его в настройках принтера в куре и много раз жать кнопку остановки печати. И не всегда помогает.

**Comment by Elkin-Vasily** [comment]
According to your log file you have got custom printer firmware that works with wifi module not correctly. So after printing is finished wifi module tells that printer is still in "PRINTING" status. Just change the firmware, or make an issue in firmware's repository.
