### ISSUE TITLE
Plugin freezes after canceling download

### ISSUE THREAD

**Issue by Engi23** [Jeredian/mks-wifi-plugin#27]
If I click "Print" and during the download process I click "cancel" the plugin stops sending files to the printer.
Often I press print and notice that I forgot to turn on some kind of setting. The connection with the printer is preserved and I see the current temperatures, but the files are no longer sent to print. The restart of the chicken solves the problem, restarting the printer gives nothing.
После нажатия "Печатать через принтер" и в процессе загрузки нажатии "отмена" плагин больше не отправляет файлы на принтер. Иногда плагин просто перестает отправлять файлы на принтер. Появляется бегунок "sending data" и ничего не происходит.
Установил файлы с данного репозитария, проблема осталась но немного видоизменилась. Теперь явно видно что после отправки на печать и отмены загрузки плагин думает что идет печать. Но нажатие "прервать печать" в разделе мониторинга ни к чему не приводит

**Comment by Jeredian** [comment]
Привет. 
Как временное решение можно попробовать через меню отключить и и подключить принтер.  Находиться это в настройках плагина что в настройках текущего принтера.
Чтобы исправить это нужно смотреть https://github.com/Jeredian/mks-wifi-plugin/blob/master/MKSWifiPlugin/MKSOutputDevice.py
В методах которые используют сокет и отправку файла.

https://github.com/Jeredian/mks-wifi-plugin/blob/6edac06388a3fadbebf769b08ad3cd5991c75d3a/MKSWifiPlugin/MKSOutputDevice.py#L1086
https://github.com/Jeredian/mks-wifi-plugin/blob/6edac06388a3fadbebf769b08ad3cd5991c75d3a/MKSWifiPlugin/MKSOutputDevice.py#L1311

Можно также при отмене печати добавить эту строку. 
self._isPrinting = False
