### ISSUE TITLE
Checkbox Bug

### ISSUE THREAD

**Issue by shadowpulse-alt** [Jeredian/mks-wifi-plugin#280]
### Plugin Version

1.3.1

### Cura Version

4.12.1

### Platform

Windows 11

### Printer

Wanhao D12 300

### Reproduction steps

By deactivating the box "print job" during the sending of the file the printing starts anyway after the transfer of the gcode file to the machine.

### Actual results

The printing starts anyway after the transfer of the gcode file to the machine.

### Expected results

Printing should not start.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture d’écran 2022-02-20 180036](https://user-images.githubusercontent.com/48736803/154854498-afa98b29-0945-43f6-9159-720475a4b654.jpg)

**Comment by Jeredian** [comment]
@ElectroFactory , thanks for the issue. It will be solved in #271 .
As a workaround, you can try to reinstall the plugin at the Cura market. ( remove plugin, restart Cura and install it again )
