### ISSUE TITLE
Support new Cura 5.0 updates

### ISSUE THREAD

**Issue by Jeredian** [Jeredian/mks-wifi-plugin#287]
https://github.com/Ultimaker/Cura/releases/tag/5.0-beta

**Comment by ParkerK** [comment]
Is there any way we can test the current version? In the past, I've been able to tweak `plugin.json` to trick the plugin to work with a newer Cura version before an update for the plugin was released, but I wasn't sure if 5.0 was the same.

Edit: Nope. It looks like you need QT6 now, and a lot of the widget properties have changed, so it looks like 5.0 beta breaks a lot of it.

**Comment by Jeredian** [comment]
Short update: Develop branch updated via PR from @ParkerK , with Qt6 migration changes.
On **Monday** I will test it on OSX and Windows, and if all comes ok will provide new release.
Since these changes our plugin will support only **Cura 5.0** and newer.

I will try to keep in Cura Marketplace _1.3.2_ version only for 4.*+ Cura, but I'm not sure that is possible because of inner publish process. Anyway, I will keep you informed.

**Comment by kadorito** [comment]
Hello, I can't find any version on cura marketplace currently, is this normal ?

**Comment by Jeredian** [comment]
@kadorito , yes, because we didn't released support for Cura 5, yet. 
But if you use Cura 4.* the 1.3.2 should be available for you, if it's not - please create a separated ticket.

**Comment by kadorito** [comment]
I'm using cura 5, I understand why then :-)

**Comment by ParkerK** [comment]
> Short update: Develop branch updated via PR from @ParkerK , with Qt6 migration changes. On **Monday** I will test it on OSX and Windows, and if all comes ok will provide new release. Since these changes our plugin will support only **Cura 5.0** and newer.
> 
> I will try to keep in Cura Marketplace _1.3.2_ version only for 4.*+ Cura, but I'm not sure that is possible because of inner publish process. Anyway, I will keep you informed.


PR https://github.com/Jeredian/mks-wifi-plugin/pull/294 will make it so 1.3.3+ will support both 4 and 5 if you want to go that route :). if not, feel free to ignore/reject

**Comment by iqubik** [comment]
Are looking forward to. And the bug with cyclic disconnection / connection of the printer on the old version has not gone away.

**Comment by Cameron18556** [comment]
so does this plugin work to see the pictures on my screen?

**Comment by tpimh** [comment]
Just updated to Cura 5.0, and couldn't install the plugin.

https://marketplace.ultimaker.com/app/cura/plugins/Jeredian/MKSWifiPlugin => "The given author does not exist."

Manual installation worked fine.

**Comment by Jeredian** [comment]
@tpimh , You are right, you can't find our plugin directly on Market, because as default it shows up plugin for latest Cura, and as you can see we just merged last fixes yesterday. For now you can use manual installation from the develop brach.

We will provide new release of the plugin soon.

**Comment by tpimh** [comment]
Thank you for clarification! As I mentioned, manual installation worked perfectly.
