### ISSUE TITLE
[Cura 4.7.0-beta] No extruder temperature in 'Monitor' session

### ISSUE THREAD

**Issue by protywu** [Jeredian/mks-wifi-plugin#29]
Application version
4.7.0-beta

Platform
Win 10, 64 bit.

Reproduction steps
Simply open Cura 4.7-beta and click on the 'Monitor' tab.
Also tried running Cura after powering on the printer so that the printer was automatically connected to Cura when Cura is up.

Actual results
The 'extruder temperature' session is missing.

Expected results
The 'extruder temperature' session should show up as in the versions before 4.7.0-beta.

**Comment by Elkin-Vasily** [comment]
Can you check this with the latest commit in this repo?

**Comment by Elkin-Vasily** [comment]
Looks like this issue is obsolete
