### ISSUE TITLE
Cura 5.0, MKS Plugin 1.4.0. Cannot connect to machine.

### ISSUE THREAD

**Issue by FedorSosnin** [Jeredian/mks-wifi-plugin#315]
### Plugin Version

1.4.0

### Cura Version

5.0

### Platform

Mac OSX 13.2.1 (M1 Max)

### Printer

Kywoo3D Tycoon

### Reproduction steps

1.Install app via .curapackage file
2. Open plugin (After restarting Cura)
3. Add IP address
4. Click "Connect"

### Actual results

Nothing happens after clicking connect. Tried reinstalling both manually and via package. 

### Expected results

Connect to plugin

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by Elkin-Vasily** [comment]
Hi! Try this:

1. Install app via .curapackage file
2. Open plugin (After restarting Cura)
3. Add IP address
4. Select string with IP address
5. Click "Connect"

**Comment by FedorSosnin** [comment]
I'm sorry, I didnt include that in my steps by accident but step 4 should have been there. After selecting the IP wasn't working I tried adding the name, in my case "Kywoo3D", and got the same result.

**Comment by Elkin-Vasily** [comment]
Ok, attach a log-file please

**Comment by iqubik** [comment]
Also get this bug on flsun q5

**Comment by iqubik** [comment]
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8862287/cura.log)
2022-06-08 17:08:59,123 - DEBUG - [MainThread] MKSWifiPlugin.MKSOutputDevicePlugin.mks_current_ip_check [78]: mks_current_ip_check called
2022-06-08 17:08:59,210 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [431]: file:///C:/Program Files/Ultimaker Cura 5.0.0/share/cura/plugins/MonitorStage/MonitorMain.qml:28: TypeError: Cannot read property 'configuredConnectionTypes' of null
2022-06-08 17:08:59,218 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2022-06-08 17:08:59,222 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [431]: file:///C:/Program Files/Ultimaker Cura 5.0.0/share/cura/plugins/MonitorStage/MonitorMain.qml:28: TypeError: Cannot read property 'configuredConnectionTypes' of null
2022-06-08 17:08:59,226 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2022-06-08 17:08:59,306 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [431]: file:///C:/Program Files/Ultimaker Cura 5.0.0/share/cura/resources/qml/WelcomePages/AddLocalPrinterScrollView.qml:237:25: Unable to assign QString to QRegularExpression

**Comment by FedorSosnin** [comment]
> Ok, attach a log-file please

Sure thing. Here is mine:

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8862618/cura.log)

**Comment by iqubik** [comment]
Так же чистый лог. Без дополнительных плагинов. Несколько запусков
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8862785/cura.log)
Что интересно так и 4 версия перестала подключаться к принтеру в отличии от прюшаслайсера и её плагина

**Comment by iqubik** [comment]
У вас написано что плагин для mks tft 4.0 а на flsun q5 экран меньше. И в последней версии и в прошлых теперь вообще ничего не работает. Ни в 4 куре ни в 5 ни на одной из версий ничего не работает.

**Comment by iqubik** [comment]
Здесь кто нибудь есть:?

**Comment by iqubik** [comment]
Я разобрался. Вроде работает. Сбросил виндовс к заводу. Думаю дело было в настройках приоритета траффика в windows. Поднимал ubuntu на windows 10 через wsl2 и там был ряд команд через powershell по работе с пакетами. Думаю что эти команды как то могли нарушить работу плагина.

**Comment by iqubik** [comment]
Нет, после первой же перезагрузки опять вообще никакой реакции. Даже нет сообщений о реконнекте. Просто тишина.

**Comment by iqubik** [comment]
нашёл интересную закономерность. Создал нового пользователя в windows 10 и поставил 5 версию с плагином из магазина - работает, а под основным пользователем нет.
Прилагаю оба лога с идентичными конфигурациями - чистая установка + плагин. Первый запуск

Не работает ничего:
[NWcura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8919692/NWcura.log)

Всё работает:
[Wcura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8919693/Wcura.log)
.

**Comment by iqubik** [comment]
Проблема была в Lantern VPN. Даже когда просто иконка отключенного Lantern висит в трее плагин не будет работать. Lantern - выход - всё ок.

**Comment by FedorSosnin** [comment]
Interesting find...for Windows.

The problem still exists with or without VPN on OSX 13.2.1.

**Comment by Elkin-Vasily** [comment]
> Interesting find...for Windows.
> 
> The problem still exists with or without VPN on OSX 13.2.1.

Try to use this version: https://github.com/Jeredian/mks-wifi-plugin/tree/issue-316

I cannot reproduce this bug, so I need some help with testing.
