### ISSUE TITLE
Flying Bear Ghost 5 disconnecting/connecting constantly

### ISSUE THREAD

**Issue by pretenda** [Jeredian/mks-wifi-plugin#336]
### Plugin Version

1.4.0

### Cura Version

4.13.1, 5.0.0, 5.1.0

### Platform

Windows 10 / MacOS 12.4

### Printer

Flying Bear Ghost 5

### Reproduction steps

1. Slice a file, send it to the printer
2. Close Cura
3. Reopen Cura while the printer is still printing
4. Observe!

### Actual results

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2951308/178143442-1faef5a4-8eff-44c0-ace2-a41f0c84a14a.png">

This happened seemingly sporadically with 4.13.1, but i am having pretty consistent issues with 5.1.0.
It will connect and disconnect constantly (The disconnected time is very short - milliseconds). I've had this issue with both Windows 10 and MacOS 12.4. 

### Expected results

Ideally wouldn't disconnect/reconnect all the time!

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/9078970/cura.log)

**Comment by Elkin-Vasily** [comment]
This was fixed in 1.4.1.

Install this version manually from GitHub,or just wait a few days till it will be checked by Ultimaker and published in Market.
