### ISSUE TITLE
“Start printing after uploading files” doesn't work

### ISSUE THREAD

**Issue by qq331212627** [Jeredian/mks-wifi-plugin#357]
### Plugin Version

1.4.1

### Cura Version

5.1.0

### Platform

win10

### Printer

two trees sapphire plus

### Reproduction steps

Restart cura

Cancel and reselect print after upload

Reinstall the plug-in

Change to another PC and cura version

### Actual results

the same wrong

### Expected results

Start printing after uploading files

### Checklist of files to include

- [ ] Log file

### Additional information & file uploads

As above

**Comment by Elkin-Vasily** [comment]
Attach a log please

**Comment by qq331212627** [comment]
The problem has been solved.

The reason for the error is the Chinese file name used



逐日
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jeredian/mks-wifi-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月26日(星期六) 晚上7:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jeredian/mks-wifi-plugin] “Start printing after uploading files” doesn't work (Issue #357)





 
Attach a log please
