### ISSUE TITLE
Printing Time and Estimated Time left broke after Estimiated time left is shown

### ISSUE THREAD

**Issue by umbo-s** [Jeredian/mks-wifi-plugin#364]
### Plugin Version

1.4.1 (same problem with 1.2.0)

### Cura Version

5.2( same problem with 4.7)

### Platform

windows 11( same problem with win 10)

### Printer

Flying Bear Ghost 5

### Reproduction steps

1.i slice my model
2.I click on the button "PRINT OVER FLYING BEAR GHOST 5"
3.The gcode is sent successfully to the printer
4.The printer starts correctly printing

### Actual results

I noticed that the time goes absolutelly crazy after the estimated time is (i think, calculated and) shown.
In the first few minutes, when the percentege is not shown, the "printing time" is printed correctly,but after the Estimated time is printed, the time goes crazy...
In particular i noticed that the printing time update to 08:50:00, then this values flactuate in a random(form my point of view) value, until it reches around 4:50:00 (sometimes) then for the rest of the printing time it increase of 00:08:20 each 5 seconds (8 minutes and 20 sec corrisponds to 500 sec).
All of this while the "estimated time" increse by 00:08:15 each 5 sec(495 sec). 

### Expected results

I wold exprect that in the printing time shows the actual printing time

### Checklist of files to include

- [ ] Log file

### Additional information & file uploads

I will attach here the log file(in this moment im printing  a pice form aound 00:29:00)
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/10200155/cura.log)
![image](https://user-images.githubusercontent.com/32361034/206857443-bd43972e-8bd7-4b48-ac43-2e4111d1e9be.png)

**Comment by tarwirdur** [comment]
"Printing Time" in Cura is not "Elapsed time". It is "approximate total print time".
So `actual elapsed time` = `Printing Time` - `Estimated time left`.

There was related issue in Cura https://github.com/Ultimaker/Cura/issues/10445 but it was closed as 'Won't fix'
