### ISSUE TITLE
No preview on Elegoo Neptune 3 Pro

### ISSUE THREAD

**Issue by jaegerschnitzel** [Jeredian/mks-wifi-plugin#365]
### Plugin Version

1.4.1

### Cura Version

5.2.1

### Platform

Windows 10

### Printer

Elegoo Neptune 3 Pro

### Reproduction steps

On my Elegoo Neptune 3 Pro no preview is shown. I tried with the following settings:

![grafik](https://user-images.githubusercontent.com/4368865/210959894-f02d5913-c3f5-4ddf-b9db-74d2e88d2594.png)

With Elegoo Cura it's and inbuild plugin version 1.0.2 it's working fine.

### Actual results

no preview on printer

### Expected results

preview shown on printer

### Checklist of files to include

- [ ] Log file

### Additional information & file uploads

![grafik](https://user-images.githubusercontent.com/4368865/210960588-088c709e-4740-45d3-b61d-9eb2b42ec6be.png)

**Comment by boehser-enkel** [comment]
Same here. I used default values

**Comment by ErockSaint** [comment]
I'm stuck in the same place on a Neptune 3 Plus. Doesn't seem to be much of a concern here though. Plugin version 1.4.2, set as active for the printer in settings, same preview settings as you have used above, and I don't get the save as tft option. Read somewhere here it was on the save file options(but that was a few versions back), I have about 5 options, none of them are tft. Save as tft works as it should, and shows a preview, when saving in Elegoo Cura.

**Comment by sex-ray** [comment]
How to use this plugin in Elegoo Neptune 3 Pro

**Comment by Torrosua** [comment]
Same for me. No actions fixed the issue =((

**Comment by finict** [comment]
@jaegerschnitzel @boehser-enkel @ErockSaint @xieyun32 @Torrosua 
Due to ELEGOO's proprietary encoding, a specific binary file is required to use the preview
Check my fork which works with latest Cura
https://github.com/finict/mks-wifi-plugin-N3

**Comment by jaegerschnitzel** [comment]
@finict 
Thank you very much it's working fine :)
