### ISSUE TITLE
Support model preview for Elegoo Neptune and Artillery Sidewinder series

### ISSUE THREAD

**Issue by Kungvald** [Jeredian/mks-wifi-plugin#366]
### Plugin Version

1.4.2

### Cura Version

5.2.2

### Platform

windows 11

### Printer

Elegoo Neptune 3 Plus

### Reproduction steps

I installed the plugin from the marketplace.

### Actual results

i did not get any errors but the abillity to save .tft file and ghet a thumbnail in the printer is not there.

### Expected results

I cant view picture of the print in my printer like if i use the elegoo cura slicer, where your older version of plugin is installed.

### Checklist of files to include

- [ ] Log file

### Additional information & file uploads

anyone working on a new version?

**Comment by sex-ray** [comment]
How to use this plugin in Elegoo Neptunne 3 Plus

**Comment by halbik** [comment]
What motherboard and screen does your printer have?

**Comment by finict** [comment]
Due to ELEGOO's proprietary encoding, a specific binary file is required to use the preview
Check my fork which works with latest Cura
https://github.com/finict/mks-wifi-plugin-N3

**Comment by Jeredian** [comment]
It looks like Elegoo uses the same encoding as Artillery (Sidewinder X3, etc). After a quick search, I found that this encoding can be achieved by a public .py version of the same lib. 
We will add support for both printer manufacturers in next plugin release.

Also for Elegoo users, I can suggest to take a look on https://github.com/Molodos/ElegooNeptuneThumbnails plugin.
