### ISSUE TITLE
Add Port with the address

### ISSUE THREAD

**Issue by danielscatigno-ncpc** [Jeredian/mks-wifi-plugin#369]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I would like to have an option to input the port of the connection

### Describe alternatives you've considered

THere is no alternative, if you have a remote connection and the port is different than the original one, it will not work

### Affected users and/or printers

People who changed the default port and the ones with remote connection with a redirect port

### Additional information & file uploads

The easiest way to do it would be allow the user to enter the entire address, 
like myhosname.com:9090

**Comment by Jeredian** [comment]
@danielscatigno-ncpc , thanks for the feature request. This looks like an interesting idea
