### ISSUE TITLE
Cura periodically freezes if printer is turned off

### ISSUE THREAD

**Issue by Troutzorz** [Jeredian/mks-wifi-plugin#38]
Cura Version 4.7.1
Printer: Flsun QQ-S Pro
Wifi Plugin Version: commit 9efec8f / pull request #37 

The problem occurs when cura is open and the printer is off. Cura's UI freezes for about 2 seconds every 2 seconds. This effects the main window, 3d build preview, all menus, and even pop-out menus. This is very disruptive to the user experience. When the printer is turned on and boots up, cura returns to expected behavior. 
I suspect the wifi plugin is searching for the printer on the main UI thread and blocking the UI from updating. I recommend searching for the printer in a background thread or figuring out some sort of async mechanism to run the search.

**Comment by berberic2** [comment]
I know it’s easy to talk big – sorry for that…

Possible no UI „fixes“ would be:
· giving up after 10 failed attempt, or
· after some failes increase interval to one attempt every X minutes.
I would prefer a „connect“ button so.
