### ISSUE TITLE
Save as TFT file bypasses post-processing scripts

### ISSUE THREAD

**Issue by BeansIsFat** [Jeredian/mks-wifi-plugin#41]
When using the *Save as TFT* feature, any enabled post-processing scripts are bypassed. For example, using the built-in *Display Progress On LCD* script and clicking on *Percentage* should embed M73 commands at every layer showing the percentage completion. This works fine when using the normal *Save* commands in Cura. When using the *Save as TFT* feature of this plugin, that script is completely ignored.

**Comment by adripo** [comment]
I can confirm that. The trick for me is to save the file using the normal save and then use the save as TFT. For some reason if you use the commands in this order, the second will work fine.
