### ISSUE TITLE
No printer controls in monitor tab

### ISSUE THREAD

**Issue by martosource** [Jeredian/mks-wifi-plugin#412]
### Plugin Version

1.4.5

### Cura Version

5.7.0

### Platform

Windows 11

### Printer

Flsun QQ-S Pro

### Reproduction steps

Open Cura
I can see the printer contected message.
Swtich the monitor tab and it is blank

### Actual results

![Screenshot 2024-04-15 155809](https://github.com/PrintMakerLab/mks-wifi-plugin/assets/1441735/1441e9f9-9bd1-42eb-9b97-10ec7eefabaf)

### Expected results

To see the print control buttons.

### Checklist of files to include

- [X] Log file

### Additional information & file uploads

[cura.log](https://github.com/PrintMakerLab/mks-wifi-plugin/files/14974642/cura.log)

**Comment by Jeredian** [comment]
I can't reproduce in version 1.4.5 on macOS
![image](https://github.com/PrintMakerLab/mks-wifi-plugin/assets/9591166/e2bfaef7-39b1-4e5e-b5a8-1a085b73c549)

**Comment by Jeredian** [comment]
@martosource , after short investigation I found that you're using `Moonraker`,  when it's connected it rewrites Monitor screen. 
![image](https://github.com/PrintMakerLab/mks-wifi-plugin/assets/9591166/84220de2-88af-434d-8af2-1d087c64b92f)
This is the screen from `Moonraker`, not from mks-wifi.

I can suggest to remove connection at the "Connect Moonraker" settings dialog, to be able to work with our plugin monitor tab
![image](https://github.com/PrintMakerLab/mks-wifi-plugin/assets/9591166/6ac0653b-b6fd-4fde-94d1-7da5e37700ba)

**Comment by martosource** [comment]
@Jeredian thank you, all sorted.
