### ISSUE TITLE
Having problems to see printing times

### ISSUE THREAD

**Issue by Anthill666** [Jeredian/mks-wifi-plugin#48]
Hi
I'm having problems to see printing time and time remaining 
with the mks-wifi-plugin in Cura (4.8)
something seems to be in the way :-D
everyyhing else seems to work

![Cura_mks_plugin](https://user-images.githubusercontent.com/77205342/104104302-7f148780-52a7-11eb-8bdd-6fa7d1840e43.jpg)

**Comment by Jeredian** [comment]
Hi @Anthill666,
Can you try to use the latest from the master?
After #47 it can be already solved.

**Comment by Anthill666** [comment]
Yes, now it looks alot better
I previously used the version on marketplace (installed it 2 days ago), but with 
the latest from the master I can finally see everything, thanks
