### ISSUE TITLE
Cura freeze when plugin is enabled

### ISSUE THREAD

**Issue by 1101101011011110** [Jeredian/mks-wifi-plugin#74]
The plugin works correctly but it makes cura freezing 1-2 seconds every 8-10 seconds. It gets worst if printer is not connected.

Cura 4.8.0.
MKS Wifi 1.1.2
Windows 10

**Comment by Elkin-Vasily** [comment]
Duplicates #36.

It was fixed already.

Try to use latest commit from devel branch or just wait a few weeks for a new release in Cura Market.

**Comment by 1101101011011110** [comment]
Sorry, I did checked open issues but not closed ones!

I'll wait for nest release. Thank you!
