### ISSUE TITLE
[BUG] Can't see the 2nd nozzle

### ISSUE THREAD

**Issue by cprobst87** [Jeredian/mks-wifi-plugin#79]
Hello,

I have a MKS GEN_L V1.0 Board with TFT32 and two nozzels. Printing is good with both nozzles, no problems here.

But: I can't see the 2nd nozzle in the cura plugin:
![image](https://user-images.githubusercontent.com/11303620/105723694-5dfa9a80-5f27-11eb-9b86-71943e38bdee.png)

TFT32, TFTWifi, Config:
![image](https://user-images.githubusercontent.com/11303620/105723641-4cb18e00-5f27-11eb-8a27-d5abc352f56d.png)

Marlin 2.0.7.2
TFT 3.0.6
Wifi 1.0.4
MKS Cura Plugin V4.4

I can see both extruders on the TFT, only the plugin doesn't show the 2nd. 

Putty connection (to Wifi module at 192.168.0.23) shows RAW:
T:45 /0 B:24 /0 T0:45 /0 T1:23 /0 @:0 B@:0

I think the plugin looks at the first "T" and "B" and not at "T0" and "T1".

Thanks for helping!
Chris

**Comment by Elkin-Vasily** [comment]
Try this with the latest commit in develop from this repo. I think it should fix this.

**Comment by cprobst87** [comment]
Thank you :-) , but.... it's the same:
![image](https://user-images.githubusercontent.com/11303620/105731140-60f98900-5f2f-11eb-8737-a3c48b2a6ead.png)

**Comment by Elkin-Vasily** [comment]
Ok I will try to figure out what happens.

**Comment by cprobst87** [comment]
Ok, I have a solution:
MKSOutputDevice.py, I added this lines (but that's not good for single nozzle machines):
![image](https://user-images.githubusercontent.com/11303620/105766561-340e9b80-5f5a-11eb-9e07-2535cb3e1b00.png)

Also add at line 184 "2" instead of "1": 
 self._number_of_extruders = 2
The same at line 107:
self._num_extruders = 2

**Comment by Elkin-Vasily** [comment]
It will be better to use `CuraApplication.getInstance().getGlobalContainerStack().getProperty("machine_extruder_count", "value")` instead of 2

**Comment by Elkin-Vasily** [comment]
<img width="465" alt="Screenshot 2021-01-26 at 00 23 07" src="https://user-images.githubusercontent.com/812359/105767879-ab4d2b00-5f6c-11eb-9885-aed76621abea.png">
And this for section on your screenshot.

I will spend some more time to fix this issue, do not worry)

**Comment by cprobst87** [comment]
Great, thank you!

**Comment by Elkin-Vasily** [comment]
I think I have fixed this issue, but I have no double extruder printer, so I cannot test it properly. Can you test it for me?

Here is the branch with fixes: https://github.com/Jeredian/mks-wifi-plugin/tree/issue-79

I need you to test:
- e0 and e1 preheat/cancel preheat;
- e0 and e1 jog position.

**Comment by Elkin-Vasily** [comment]
I had updated this branch ones more

**Comment by cprobst87** [comment]
Prehead is OK, jog works.
Cancel preheat E0 works. E1 cancel but the temperature isn't 0:
![image](https://user-images.githubusercontent.com/11303620/106382049-1bb8d980-63bd-11eb-838a-4a5717a8461b.png)

One little thing:
![image](https://user-images.githubusercontent.com/11303620/106381898-2f177500-63bc-11eb-8e8b-8673f754b76c.png)
Because of this mouse-over-effect I have to click several times to get the button...

**Comment by Elkin-Vasily** [comment]
Tnx, I know about tooltip bug, but cannot do anything about it right now (it is Cura tooltips, by the way please try this with your printer connected directly with USB cable, does tooltips look the same?).

Reset of the Extruder 2 target temperature works same for me, looks like this is a problem in MKS WiFi module... Need to create issue for them... Because we got temperature from here T:45 /0 B:24 /0 T0:45 /0 T1:23 /**202** @:0 B@:0 and it stays 202 for your case.
