### ISSUE TITLE
Cura hangs when not connected to printer

### ISSUE THREAD

**Issue by szabota** [Jeredian/mks-wifi-plugin#89]
There is a problem with plugin version 1.1.2:
Until a connection to the printer is established, Cura freezes for 2 seconds every 2 seconds.
This is noticeable if, for example, you rotate a model loaded into Cura.
The hang goes away as soon as a WiFi connection is established with the printer.
It turns out that in order to work normally in Cura, now you need to keep the printer always on.
The problem arose immediately after updating the plugin to version 1.1.2. Before that, this was not observed.
When the plugin is rolled back to version 1.0.2, the problem disappears.
Cura version 4.8.0 & FlyingBear 4S.
---
С версией плагина 1.1.2 есть проблема:
Пока не установлено подключение к принтеру, Cura зависает на 2 секунды с периодичностью раз в 2 секунды.
Это заметно, если например повращать загруженную в Cura модель.
Зависание проходит, как только устанавливается WiFi-соединение с принтером.
Получается, чтобы нормально работать в Cura теперь нужно держать принтер всегда включенным.
Проблема возникла сразу, после обновления плагина на версию 1.1.2. Перед этим такого не наблюдалось.
При откате плагина на версию 1.0.2, проблема исчезает.
Cura версии 4.8.0 & Мишка 4S.

**Comment by Elkin-Vasily** [comment]
This problem duplicates #38 and was solved in current plugin version. I could get the latest from level or just wait a few weeks until this version will be available on Cura Market.
_
Эта проблема дублирует #38 и решена в текущей версии плагина. Можете взять последнюю версию из ветки devel или подождать пару недель, она появится в маркете Cura.
